
-- SQL script to check and add missing columns from schema.ts
-- Excludes sys_user table as requested

-- Categories table
ALTER TABLE categories ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT 'fa-folder';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);

-- Products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price DECIMAL(18,2) NOT NULL DEFAULT 0.00;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES categories(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type INTEGER NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS track_inventory BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate_name TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_includes_tax BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS after_tax_price DECIMAL(18,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS before_tax_price DECIMAL(18,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS floor VARCHAR(50) DEFAULT '1';
ALTER TABLE products ADD COLUMN IF NOT EXISTS zone VARCHAR(50) DEFAULT 'A';
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'Cái';
ALTER TABLE products ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);

-- Transactions table
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS transaction_id TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS tax DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT 'cash';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS amount_received DECIMAL(10,2);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS change DECIMAL(10,2);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS cashier_name TEXT NOT NULL DEFAULT '';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS invoice_id INTEGER REFERENCES invoices(id);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Transaction items table
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS transaction_id INTEGER REFERENCES transactions(id);
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS product_id INTEGER REFERENCES products(id);
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS product_name TEXT NOT NULL DEFAULT '';
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE transaction_items ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);

-- Employees table
ALTER TABLE employees ADD COLUMN IF NOT EXISTS employee_id TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'cashier';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS hire_date TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);

-- Attendance records table
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS employee_id INTEGER REFERENCES employees(id);
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS clock_in TIMESTAMPTZ;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS clock_out TIMESTAMPTZ;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS break_start TIMESTAMPTZ;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS break_end TIMESTAMPTZ;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS total_hours DECIMAL(4,2);
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS overtime DECIMAL(4,2) DEFAULT 0.00;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'present';
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Store settings table
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS store_name TEXT NOT NULL DEFAULT 'EDPOS 레스토랑';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS store_code TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS domain TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS price_list_id INTEGER REFERENCES price_lists(id);
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS business_type TEXT DEFAULT 'restaurant';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS pin_code TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS password TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS parent TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS type_user INTEGER DEFAULT 0;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS open_time TEXT DEFAULT '09:00';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS close_time TEXT DEFAULT '22:00';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS gold_threshold TEXT DEFAULT '300000';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS vip_threshold TEXT DEFAULT '1000000';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS price_includes_tax BOOLEAN DEFAULT false;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS default_floor TEXT DEFAULT '1';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS default_zone TEXT DEFAULT 'A';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS floor_prefix TEXT DEFAULT '층';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS zone_prefix TEXT DEFAULT '구역';
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS is_edit BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS is_cancelled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Suppliers table
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS contact_person TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS bank_account TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS payment_terms TEXT DEFAULT '30일';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Customers table
ALTER TABLE customers ADD COLUMN IF NOT EXISTS customer_id TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tax_code TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS membership_tier TEXT DEFAULT 'bronze';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS membership_level TEXT DEFAULT 'BRONZE';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS total_spent DECIMAL(12,2) DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_visit TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Tables table
ALTER TABLE tables ADD COLUMN IF NOT EXISTS table_number VARCHAR(50);
ALTER TABLE tables ADD COLUMN IF NOT EXISTS capacity INTEGER DEFAULT 4;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'available';
ALTER TABLE tables ADD COLUMN IF NOT EXISTS floor VARCHAR(50) DEFAULT '1';
ALTER TABLE tables ADD COLUMN IF NOT EXISTS zone VARCHAR(50) DEFAULT 'A';
ALTER TABLE tables ADD COLUMN IF NOT EXISTS qr_code TEXT;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE tables ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Orders table
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS table_id INTEGER REFERENCES tables(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS employee_id INTEGER REFERENCES employees(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id INTEGER REFERENCES customers(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_tax_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_count INTEGER DEFAULT 1;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS is_paid BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS einvoice_status INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS template_number VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS symbol VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sales_channel TEXT NOT NULL DEFAULT 'table';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS price_include_tax BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ordered_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS served_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Order items table
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS order_id INTEGER REFERENCES orders(id);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_id INTEGER REFERENCES products(id);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS quantity NUMERIC(8,4) NOT NULL DEFAULT 1;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_price DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS tax DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS price_before_tax DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);

-- Purchase receipts table
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS receipt_number TEXT;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS supplier_id INTEGER REFERENCES suppliers(id);
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS employee_id INTEGER REFERENCES employees(id);
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS purchase_date DATE;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS actual_delivery_date DATE;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS purchase_type TEXT;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS subtotal DECIMAL(18,2) NOT NULL DEFAULT 0.00;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS tax DECIMAL(18,2) NOT NULL DEFAULT 0.00;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS total DECIMAL(18,2) NOT NULL DEFAULT 0.00;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS is_paid BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS payment_amount DECIMAL(18,2);
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE purchase_receipts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Purchase receipt items table
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS purchase_receipt_id INTEGER REFERENCES purchase_receipts(id);
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS product_id INTEGER REFERENCES products(id);
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS product_name TEXT NOT NULL DEFAULT '';
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS received_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS unit_price DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS total DECIMAL(15,2) NOT NULL DEFAULT 0.00;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS discount_percent DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS row_order INTEGER DEFAULT 0;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE purchase_receipt_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Invoices table
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS trade_number VARCHAR(50);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS template_number VARCHAR(50);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS symbol VARCHAR(20);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_id INTEGER REFERENCES customers(id);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_tax_code VARCHAR(20);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_address TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(20);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS customer_email VARCHAR(100);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_method INTEGER NOT NULL DEFAULT 1;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_date TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'draft';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS einvoice_status INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_status INTEGER NOT NULL DEFAULT 1;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Payment methods table
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS name_key VARCHAR(50);
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS type VARCHAR(50) NOT NULL DEFAULT 'cash';
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT '💵';
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Price lists table
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS code VARCHAR(50);
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ;
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS valid_to TIMESTAMPTZ;
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS store_code VARCHAR(50);
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

-- Update default values for existing records
UPDATE products SET unit = 'Cái' WHERE unit IS NULL;
UPDATE products SET floor = '1' WHERE floor IS NULL;
UPDATE products SET zone = 'A' WHERE zone IS NULL;
UPDATE tables SET floor = '1' WHERE floor IS NULL;
UPDATE tables SET zone = 'A' WHERE zone IS NULL;
UPDATE orders SET discount = 0.00 WHERE discount IS NULL;
UPDATE order_items SET discount = 0.00 WHERE discount IS NULL;
UPDATE order_items SET tax = 0.00 WHERE tax IS NULL;
UPDATE store_settings SET default_zone = 'A' WHERE default_zone IS NULL;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);

-- Log completion
SELECT 'Schema check and column addition completed successfully!' AS result;
